### ISSUE TITLE
Create deploy script

### ISSUE THREAD

**Issue by alexkramer** [alexkramer/force-vue#2]
Script should build the project and copy the dist file over to the gh-pages and push the result

**Comment by alexkramer** [comment]
A quick google search seems to yield a couple of different options people have found to automate this process.

**Comment by alexkramer** [comment]
This looks great @ajcann. Thanks!

**Comment by alexkramer** [comment]
Just an FYI, I tested this out and it works like a charm.

**Comment by ajcann** [comment]
Great to hear! One never knows when an environment quirk might throw you for a loop.
